### ISSUE TITLE
getlibs references gunzip, but states it requires 7zip

### ISSUE THREAD

**Issue by npruehs** [kulibali/ponyc-windows-libs#1]
Hey :) Just tried to build the pony compiler on Windows from scratch, and while there are many steps involved, each and everyone of them worked immediately. Good job there!

These's still a small thing, though: getlibs.bat line 20 references gunzip:

`gunzip --stdout %PCRE2_SRC% | tar xf -`

I guess it should depend on 7zip, according to the documentation?

**Comment by chalcolith** [comment]
gunzip is included in GnuWin32; the reference to 7-zip is out of date.

**Comment by npruehs** [comment]
Unfortunately, in Windows, it does not come as an executable? Or did my compilation go wrong?

![gunzip](https://cloud.githubusercontent.com/assets/757321/16209476/812ada28-3737-11e6-9de5-c7df5f1944d4.png)

**Comment by chalcolith** [comment]
Oops, you're correct.  I had gunzip in my path from another source.  It should work now.
